apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: '{{{M3_NAMESPACE}}}'
  labels:
    application: "{{{M3_APPLICATION}}}"
    version: '{{{M3_VERSION}}}'
    project: '{{{M3_PROJECT}}}'
  annotations:
    kubernetes.io/ingress.class: nginx
  name: "{{{M3_APPLICATION}}}"
spec:
  rules:
    - host: "ghiras-play.m3ntorship.net"
      http:
        paths:
          - backend:
              serviceName: "{{{M3_APPLICATION}}}"
              servicePort: 80
            path: /