apiVersion: v1
kind: Service
metadata:
  name: "{{{APPLICATION}}}"
  labels:
    application: "{{{APPLICATION}}}"
    version: '{{{VERSION}}}'
  namespace: '{{{NAMESPACE}}}'
spec:
  selector:
    application: "{{{APPLICATION}}}"
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{{PORT}}}
---
