FROM node:12.16.3-alpine3.11

# create application directory
RUN mkdir -p /charity-next
WORKDIR /charity-next
ARG REACT_APP_STRAPI_URL
ARG REACT_APP_STRAPI_URL_AR


# copy application files
COPY ./ .
# install dependencies
RUN yarn && yarn build

EXPOSE 3000

CMD ["yarn", "start"]