name: Push Container to Heroku

on: 
  push:
    branches:
      - feature/configure-storybook

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v1
    - run: yarn
    - run: yarn build-storybook
    - name: Login to Heroku Container registry
      env: 
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_TOKEN }}
      run: heroku container:login 
    - name: Build and push
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_TOKEN }}
      run: heroku container:push -a m3ntorship-charity-storybook web 
    - name: Release
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_TOKEN }}
      run: heroku container:release -a m3ntorship-charity-storybook web 