name: deploy to playground

on: 
  push:
    branches:
      - playground-deployment

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the code 
        uses: actions/checkout@v1
      
      # install kubectl 
      - name: install kubectl
        uses: azure/setup-kubectl@v1
      
      # configure kubectl
      - name: Kubectl configuration
        shell: bash
        run: |
          mkdir -p ~/.kube
          echo ${{ secrets.KUBE_CONFIG }} | base64 -d -i > ~/.kube/config
      
      # install moustache
      - name: install moustache
        run: |
          curl -sSL https://git.io/get-mo -o mo
          chmod +x mo
          sudo mv mo /usr/local/bin/
          echo "works" | mo
      
      # generate k8s yaml(s)
      - name: generate k8s resources from templates
        run: |
          mkdir -p ./deploy/resources
          for f in ./deploy/apply/*.yaml; do mo -s=delivery "$f" > ./deploy/resources/"$(basename $f)"; done
          kubectl apply -f ./deploy/resources